export {};

type Leg={from:string;to:string;km:string;time:string;note:string};
type Photo={id:string;src:string;title:string;author:string;license:string;licenseUrl:string;source:string};
type Day={image:string;mood:string;km:string;legs:Leg[];date:string;weekday:string;city:string;title:string;route:string;drive:string;hotel:number|null;events:string[][];food:string;rest:string;charge:string;fallback:string;places:string[]};
type Stay={city:string;dates:string;nights:number;options:{name:string;id:string;note:string;quote?:string}[]};
type Data={days:Day[];stays:Stay[];sources:string[][];chargers:string[][];checks:string[]};
type Saved={selected:number[];prices:number[];checks:boolean[];day:number};
const el=(id:string)=>document.getElementById(id)!;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const link=(url:string,label:string)=>`<a href="${escape(url)}" target="_blank" rel="noopener">${escape(label)} ↗</a>`;
const map=(name:string)=>`https://uri.amap.com/search?keyword=${encodeURIComponent(name)}&callnative=1`;
const key='shanxi-roadbook-v3';
const route=(from:string,to:string)=>'https://api.map.baidu.com/direction?'+new URLSearchParams({origin:from,destination:to,mode:'driving',region:'中国',output:'html',src:'webapp.shanxi.family'}).toString();
async function start(){
 const response=await fetch('data.json'); if(!response.ok)throw Error('data');const data=await response.json() as Data;
 let raw:Partial<Saved>={};try{raw=JSON.parse(localStorage.getItem(key)||'{}') as Partial<Saved>;}catch{}
 const state:Saved={selected:data.stays.map((s,i)=>Number.isInteger(raw.selected?.[i])&&s.options[raw.selected![i]!] ?raw.selected![i]!:0),prices:data.stays.map((_,i)=>Math.max(0,Math.min(100000,Number(raw.prices?.[i])||0))),checks:data.checks.map((_,i)=>raw.checks?.[i]===true),day:Math.max(0,Math.min(5,Number(raw.day)||0))};
 const save=()=>{try{localStorage.setItem(key,JSON.stringify(state));}catch{}};
 function renderDay(d:Day,i:number){return `<article class="day-card"><div class="day-cover"><img src="images/${escape(d.image)}.jpg" alt="${escape(d.city)}相关景点实景" loading="lazy"><div class="day-title"><p class="eyebrow">DAY 0${i+1} / 10月${i+1}日 ${d.weekday} · ${escape(d.mood)}</p><h2>${escape(d.title)}</h2><p>${escape(d.route)}</p></div></div><div class="day-summary"><strong>${escape(d.km)} km</strong><p>${escape(d.drive)}</p></div><div class="day-body"><ol class="timeline">${d.events.map(e=>`<li><time>${escape(e[0]!)}</time><h3>${escape(e[1]!)}</h3><p>${escape(e[2]!)}</p></li>`).join('')}</ol><aside><div class="sidebox"><span class="side-label">EAT LOCAL</span><h3>今天吃什么</h3><p>${escape(d.food)}</p></div><div class="sidebox"><span class="side-label">TAKE A BREAK</span><h3>给孩子留白</h3><p>${escape(d.rest)}</p></div><div class="sidebox"><span class="side-label">CHARGE UP</span><h3>补电安排</h3><p>${escape(d.charge)}</p></div><div class="sidebox warn"><span class="side-label">IF WE ARE LATE</span><h3>临场调整</h3><p>${escape(d.fallback)}</p></div></aside></div><div class="leg-list"><h3>分段驾车导航</h3><p class="small">点击打开百度驾车线路，手机可继续到地图App；同名地点先选城市与准确入口。高德地点搜索放在下方。</p>${d.legs.map(l=>`<div class="leg"><div><strong>${escape(l.from)} → ${escape(l.to)}</strong><p>${escape(l.note)}</p></div><div><b>${escape(l.km)} km</b><p>${escape(l.time)}</p></div><a class="button" target="_blank" rel="noopener" href="${escape(route(l.from,l.to))}">驾车线路 ↗</a></div>`).join('')}<div class="place-links">${d.places.map(p=>link(map(p),p+' · 高德')).join('')}</div></div></article>`;}
 function showDay(index:number){state.day=index;el('days').innerHTML=data.days.map((d,i)=>`<button data-day="${i}" class="${i===index?'active':''}" aria-pressed="${i===index}"><small>DAY 0${i+1} · ${d.date}</small>${d.city}</button>`).join('');el('day').innerHTML=renderDay(data.days[index]!,index);save();}
 el('days').addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLButtonElement>('button[data-day]');if(b)showDay(Number(b.dataset.day));});
 function budget(){const total=state.prices.reduce((a,b)=>a+b,0);const complete=state.prices.every(p=>p>0);el('total').textContent='¥'+total.toLocaleString('zh-CN');el('budget-status').textContent=!complete?'尚有未填写的酒店，当前为部分合计':total>2500?'超过原预算 ¥2,500；按实际房型价格比较':total>1750?'高于理想预算，仍在原预算区间内':'在理想住宿预算内';el('budget-status').className=total>2500?'over':'';}
 function hotels(){el('hotels').innerHTML=data.stays.map((s,i)=>{const chosen=s.options[state.selected[i]!]!;return `<article class="hotel"><small>${s.dates} · ${s.nights}晚</small><h3>${s.city}</h3><label for="hotel-${i}">酒店候选</label><select id="hotel-${i}" data-stay="${i}">${s.options.map((o,j)=>`<option value="${j}" ${j===state.selected[i]?'selected':''}>${escape(o.name)}</option>`).join('')}</select><p>${escape(chosen.note)}</p><p class="quote">${escape(chosen.quote||"此备选尚未查到对应国庆日期报价，不能保证低于¥500。")}</p>${link('https://hotels.ctrip.com/hotels/detail/?hotelId='+chosen.id+'&checkIn=2026-10-0'+(i+1)+'&checkOut=2026-10-0'+(i===3?6:i+2)+'&adult=2&children=1','携程查对应日期（核对儿童5岁）')}<label for="price-${i}">${s.nights}晚含税总价 ¥ <input id="price-${i}" type="number" min="0" max="100000" step="1" inputmode="numeric" placeholder="待核价" value="${state.prices[i]||''}" data-price="${i}"></label><small>${s.nights===2?'请填写10月4–6日两晚合计，不是单晚价格。':'请填写对应日期一晚价格。'} ${state.prices[i]!/s.nights>500?'⚠ 超过原参考¥500/晚':''}</small></article>`;}).join('');budget();}
 el('hotels').addEventListener('change',e=>{const t=e.target as HTMLInputElement;if(t.dataset.stay!==undefined){const i=Number(t.dataset.stay);state.selected[i]=Number(t.value);state.prices[i]=0;hotels();}else if(t.dataset.price!==undefined){state.prices[Number(t.dataset.price)]=Math.max(0,Math.min(100000,Number(t.value)||0));hotels();}save();});
 el('checks').innerHTML=data.checks.map((c,i)=>`<label><input type="checkbox" data-check="${i}" ${state.checks[i]?'checked':''}><span>${escape(c)}</span></label>`).join('');
 el('checks').addEventListener('change',e=>{const t=e.target as HTMLInputElement;state.checks[Number(t.dataset.check)]=t.checked;save();});
 el('sources').innerHTML=data.sources.map(s=>`<div class="source-row">${link(s[1]!,s[0]!)}<p>${escape(s[2]!)}</p></div>`).join('');
 el('chargers').innerHTML=data.chargers.map(c=>`<p>${link(c[1]!,c[0]!)}<br>${escape(c[2]!)}</p>`).join('');
 el('export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({trip:'2026-10-01至06晋北亲子自驾',savedAt:new Date().toISOString(),stays:data.stays.map((s,i)=>({city:s.city,dates:s.dates,hotel:s.options[state.selected[i]!]?.name,totalPrice:state.prices[i]||'待核价'})),checklist:data.checks.map((item,i)=>({item,done:state.checks[i]})),days:data.days},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='晋北六日路书-我的安排.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});

 const chooseRouteDay=(target:Element)=>{const g=target.closest<SVGGElement>('[data-route-day]');if(g){showDay(Number(g.dataset.routeDay));el('itinerary').scrollIntoView({behavior:'smooth'});}};
 document.querySelector('.route-map')?.addEventListener('click',e=>chooseRouteDay(e.target as Element));
 document.querySelector('.route-map')?.addEventListener('keydown',e=>{const k=e as KeyboardEvent;if(k.key==='Enter'||k.key===' '){k.preventDefault();chooseRouteDay(k.target as Element);}});
 const chargeRows=[['01','途中保定 + 正定夜间','08:00左右休息；每次留45–75分钟窗口。高速站排队长时，比较爱情广场城市超充绕行。','保定爱情广场特斯拉超级充电站'],['02','途中快充 + 忻州补足','约235km跨城，正定离开前补足，中途仍留补电。晚间开来欣悦为次日准备。','忻州开来欣悦购物广场特斯拉超级充电站'],['03','忻州满够出发 → 应县补足','实查两段174km；到站预测低于20%就提前充，晚间应县公共快充。','应县 充电站'],['04–05','大同城市补电','绿地缤纷汇为官方超充站。午休/晚饭合并补电，10/5晚准备返程。','大同绿地缤纷汇特斯拉超级充电站'],['06','返京150–180km先停','阳原—宣化沿线按导航找主站；张家口经开区超充为城市备用，比较绕行。','阳原 宣化 高速充电站']];
 el('charge-plan').innerHTML=chargeRows.map(c=>`<div class="charge-row"><span>${c[0]}</span><div><h3>${c[1]}</h3><p>${c[2]}</p>${link(map(c[3]!),c[0]==='03'||c[0]==='06'?'查沿线候选（非已确认站）':'查看站点位置')}</div></div>`).join('');
 function calc(){const r=Number((el('range') as HTMLInputElement).value),soc=Number((el('soc') as HTMLInputElement).value),km=Number((el('leg-km') as HTMLInputElement).value);el('range-out').textContent=r+' km';el('soc-out').textContent=soc+'%';if(!Number.isFinite(km)||km<=0||km>800){el('charge-result').textContent='请输入1–800公里的下一段里程。';return;}const arrive=soc-km/r*100;el('charge-result').innerHTML=`<strong>${Math.round(arrive)}% <small>估算到站余量</small></strong><p>${arrive<20?'这段应提前安排补电，或提高出发电量。':'演算余量高于20%；仍以车机预测及实时空闲为准。'}</p><span>按20%余量，你当前可安排约 ${Math.max(0,Math.floor((soc-20)/100*r))} km 再补电。</span>`;}
 ['range','soc','leg-km'].forEach(id=>el(id).addEventListener('input',calc));calc();
 const bowl=`<svg viewBox="0 0 110 80" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="2"><ellipse cx="55" cy="40" rx="43" ry="12"/><path d="M12 40Q18 70 55 71Q92 70 98 40M31 73H79M30 37Q23 22 35 11M51 35Q43 20 55 8M72 36Q64 22 76 10M81 14L26 55M90 20L37 61"/></g></svg>`;
 const food=[['正定','八大碗 · 古街晚餐','点两三道小份家常菜，崩肝供大人尝；孩子配热面或米饭。旺泉古街就近吃，不再跨城赶小商品夜市。','家庭一餐规划 ¥100–180','正定旺泉古街'],['忻州','蒸肉 · 莜面 · 羊杂','17点先吃正餐，再去铁花检票。定襄蒸肉适合分食；怕羊膻味就选莜面与家常菜。','家庭一餐规划 ¥80–150','忻州古城 定襄蒸肉'],['应县','木塔边的一碗凉粉','凉粉小份尝鲜，配馅饼、面条或热菜。晚餐不要只吃冷食；第二天早餐选酒店或附近包子粥。','家庭一餐规划 ¥60–120','应县木塔 凉粉'],['浑源','凉粉 + 热面食','小媳妇凉粉（永安西街11号）是已查候选。搭配馅饼或热菜，辣椒另放；不追求两地凉粉都打卡。','平台小媳妇约 ¥28/人，仅参考','小媳妇凉粉 浑源永安西街11号'],['大同','烧麦 · 刀削面','龙聚祥作烧麦候选，刀削面就近选店。两大一小先点一份烧麦再补面，避免分量超预期。','家庭一餐规划 ¥100–180','大同龙聚祥烧麦馆'],['大同','铜火锅 · 夜游早晚饭','想坐久一点，铜火锅配莜面；凯鸽、紫泥369作备选搜索，按酒店位置选店，避开古城核心长队。','家庭一餐规划 ¥150–250','大同紫泥369粗粮季']];
 el('food-grid').innerHTML=food.map(f=>`<article class="food-card"><div class="food-art"><span>${f[0]}</span>${bowl}</div><div class="food-content"><h3>${f[1]}</h3><p>${f[2]}</p><p class="price">${f[3]}</p>${link(map(f[4]!),f[0]==='正定'||f[0]==='忻州'||f[0]==='应县'?'查看美食区域':'查候选店与分店')}</div></article>`).join('');
 const scenes=[['yanmen','雁门关','找一找：城门为什么这么厚？看看箭孔，不必爬完整段长城。','雁门关景区北门'],['wood','应县木塔','找一找：屋檐下面层层托起的斗拱，像不像会咬合的积木？','应县木塔景区'],['hanging','悬空寺','看一看：房子怎样贴在岩壁上？在安全区域观察木柱和栈道。','悬空寺'],['yungang','云冈石窟','找一找：大佛身边的小像、乐器与飞天。一次记住一个故事。','云冈石窟'],['datong','大同古城','比一比：城墙内外有什么不同？晚间只走一小段。','大同古城永泰门']];
 el('attractions').innerHTML=scenes.map(a=>`<article class="attraction"><img loading="lazy" src="images/${a[0]}.jpg" alt="${a[1]}实景"><h3>${a[1]}</h3><p>${a[2]}</p>${link(map(a[3]!), '查看地点')}</article>`).join('');
 fetch('photos.json').then(r=>r.json()).then((photos:Photo[])=>{el('photo-credits').innerHTML=photos.map(p=>`<div class="photo-credit">${link(p.source,p.title.replace('File:',''))}<br>${escape(p.author)} · ${link(p.licenseUrl,p.license)} · 版面可能裁切</div>`).join('');}).catch(()=>{el('photo-credits').innerHTML=link('photos.json','查看照片署名文件');});
 const printAll=()=>{document.getElementById('print-all')?.remove();const block=document.createElement('div');block.id='print-all';block.innerHTML=data.days.map(d=>`<div class="print-day">${renderDay(d,data.days.indexOf(d))}</div>`).join('');el('day').after(block);};
 window.addEventListener('beforeprint',printAll);window.addEventListener('afterprint',()=>document.getElementById('print-all')?.remove());el('print').addEventListener('click',()=>window.print());showDay(state.day);hotels();
}
start().catch(()=>{el('day').textContent='路书数据暂时未加载，请刷新页面；需要联网载入行程。';});
